version: 2
jobs:
  test_on_centos7:
    docker:
      - image: centos:7
    working_directory: ~/ytkit
    steps:
      - checkout
      - run: sed -i 's|#baseurl=http://mirror.centos.org/|baseurl=http://vault.centos.org/|' /etc/yum.repos.d/CentOS-*
      - run: yum install -y perl-App-cpanminus gcc mysql-devel perl-homedir make rpm-build perl-DBD-MySQL perl-Time-Piece epel-release perl-JSON perl-Term-ReadKey
      - run: yum install -y perl-Test-MockTime perl-Carp-Always perl-Clone perl-Data-Dumper perl-Parallel-ForkManager
      - run: cpanm App::cpanminus
      - run: /usr/local/bin/cpanm --installdeps .
      - run:
          command: "make test"
          environment:
            TZ: "UTC-9"
  test_on_centos8:
    docker:
      - image: quay.io/centos/centos:stream8
    working_directory: ~/ytkit
    steps:
      - checkout
      - run: sed -i 's|#baseurl=http://mirror.centos.org/|baseurl=http://vault.centos.org/|' /etc/yum.repos.d/CentOS-*
      - run: dnf install -y perl-App-cpanminus gcc mysql-devel make rpm-build perl-DBD-MySQL perl-Time-Piece epel-release perl-JSON
      - run: dnf install -y perl-Test-MockTime perl-Data-Dumper
      - run: cpanm --installdeps .
      - run:
          command: "make test"
          environment:
            TZ: "UTC-9"
  test_on_rocky9:
    docker:
      - image: rockylinux:9
    working_directory: ~/ytkit
    steps:
      - checkout
      - run: dnf install -y perl-App-cpanminus gcc make rpm-build perl-DBD-MySQL perl-Time-Piece epel-release perl-JSON
      - run: dnf install -y perl-Test-MockTime perl-Data-Dumper
      - run: cpanm --installdeps .
      - run:
          command: "make test"
          environment:
            TZ: "UTC-9"
  test_on_ubuntu2204:
    docker: 
      - image: ubuntu:22.04
    working_directory: ~/ytkit
    steps:
      - checkout
      - run: apt update
      - run: apt install -y cpanminus gcc libmysqlclient-dev libdbd-mysql-perl libjson-perl libtest-mocktime-perl libterm-readkey-perl libparallel-forkmanager-perl
      - run: DEBIAN_FRONTEND=noninteractive apt install -y tzdata
      - run: cpanm --installdeps .
      - run:
          command: "make test"
          environment:
            TZ: "UTC-9"
workflows:
  version: 2
  test:
    jobs:
      - test_on_centos7
      - test_on_centos8
      - test_on_rocky9
      - test_on_ubuntu2204
