version: 2
jobs:
  test:
    docker:
      - image: centos:7
    working_directory: ~/ytkit
    steps:
      - checkout
      - restore_cache:
          key: v0.1.11
      - run: yum install -y perl-App-cpanminus gcc mysql-devel perl-homedir make rpm-build perl-DBD-MySQL perl-Time-Piece epel-release perl-JSON perl-Term-ReadKey
      - run: yum install -y perl-Test-MockTime perl-Carp-Always perl-Clone perl-Data-Dumper
      - run: cpanm App::cpanminus
      - run: /usr/local/bin/cpanm --installdeps .
      - save_cache:
          key: v0.1.13-5
          paths: ~/perl5
      - run:
          command: "make test"
          environment:
            TZ: "UTC-9"

workflows:
  version: 2
  test:
    jobs:
      - test
